export const CART_ACTION_TYPES = {
    ADD_TO_CART: "cart/ADD_TO_CART",
    CHANGE_IS_CART: 'cart/CHANGE_IS_CART',
    SET_CART_ITEM: 'cart/SET_CART_ITEM',
    SET_CART_COUNT: 'cart/SET_CART_COUNT',
    SET_CART_TOTAL: 'cart/SET_CART_TOTAL',
  };